_schema: _schema
paths:
  uploads: uploads
  static: ''
collections_config:
  data:
    path: _data
    name: Data
    icon: data_usage
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  id:
    type: text
    hidden: true
    cascade: true
  image-side:
    type: select
    options:
      allow-empty: false
      values:
        - left
        - right
    cascade: true
_structures:
  blocks:
    style: select
    values:
      - label: hero banner
        value:
          id: hero-banner
          image: /images/vineyard-6.jpg
          image-width: full
          image-position: bottom
          image-alt-text: vineyard-view
          main-heading: Far Niente Vineyard
          subtitle: Welcome to
      - label: Text Image Side-by-Side
        value:
          id: side-by-side
          heading: Duis Aute Irure
          paragraph: >-
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore
            aperiam ipsa perspiciatis aliquam reprehenderit id cumque fugit
            doloribus aliquid blanditiis est, facilis alias, voluptate ratione
            nisi ad et quos. Similique. Lorem ipsum dolor sit amet consectetur
            adipisicing elit. Cupiditate autem consequatur voluptatum numquam
          link-text: Sign Up
          link:
          front-image: /images/vineyard-3.jpg
          front-image-alt-text: vineyard-view
          back-image: /images/vineyard-4.jpg
          image-side: left
          decorative-border: true
      - label: Featured Text
        value:
          id: featured-text
          heading: Lorem ipsum dolor sit amet consectetur adipisicing elit.
          paragraph: >-
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores,
            cum tempora! Veritatis aliquam officia veniam, voluptates porro,
            nesciunt illum quae iusto incidunt placeat laboriosam odio iste
            harum eligendi molestiae unde! Lorem ipsum, dolor sit amet
            consectetur adipisicing elit. Sequi illo dignissimos earum rerum
            ipsam aperiam cupiditate voluptatem commodi dolorum consequuntur
            dolorem assumenda, modi iste ea ut enim, voluptas optio odio.
file_config:
  - glob:
    _inputs:
    _structures:
    _select_data:
editor:
  default_path:
timezone: America/New_York
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
