wines:
  - wine: Cabernet Sauvignon
    info: Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus quos debitis numquam accusamus eveniet! Fugiat doloribus totam esse blanditiis neque nam consequatur soluta. Tempore perferendis atque nobis quas sunt nisi!
    vintage: 2021
    blend: 
    taste: Black Cherry, Plum, Spice
    region: Central Coast
    image: /images/red-wine-transp.png
    button-text: Add to cart
    button-link: #
  - wine: Pinot Grigio
    info: Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus quos debitis numquam accusamus eveniet! Fugiat doloribus totam esse blanditiis neque nam consequatur soluta. Tempore perferendis atque nobis quas sunt nisi!
    vintage: 2021
    blend: 
    taste: Apple, Pear
    region: Veneto
    image: /images/white-wine-transp.png
    button-text: Add to cart
    button-link: #
  - wine: Chianti
    info: Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus quos debitis numquam accusamus eveniet! Fugiat doloribus totam esse blanditiis neque nam consequatur soluta. Tempore perferendis atque nobis quas sunt nisi!
    vintage: 2022
    blend: 90% Sangiovese
    taste: Dried Cherry, Black Currant, Vanilla
    region: Tuscany
    image: /images/red-wine-transp.png
    button-text: Add to cart
    button-link: #
  - wine: Cabernet Sauvignon
    info: Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus quos debitis numquam accusamus eveniet! Fugiat doloribus totam esse blanditiis neque nam consequatur soluta. Tempore perferendis atque nobis quas sunt nisi!
    vintage: 2021
    blend: 
    taste: Black Cherry, Plum, Spice
    region: Central Coast
    image: /images/white-wine-transp.png
    button-text: Add to cart
    button-link: #